name: nostrpay_wallet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  ldk_node: ^0.3.0
  bip39: ^1.0.6
  flutter_secure_storage: ^4.2.1
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
